afterClickHTML = '//*[@id="screener-criteria"]/div[2]/div[1]/div[1]/div/div[2]/div/div[2]'
filters = 'C($tertiaryColor) Mstart(12px) Cur(p) Va(m)'
screen_login = 'https://login.yahoo.com/config/login?.src=finance&.intl=us&.lang=en-US&.done=https%3A%2F%2Ffinance.yahoo.com%2Fscreener'
close_filter = '/html/body/div[1]/div/div/div[1]/div/div[2]/div/div/div[5]/div/div/div/div[2]/div[1]/div[1]/div/div[2]/div/div[3]/button'

intra = '//*[@id="screener-criteria"]/div[2]/div[1]/div[1]/div/div[2]/div/div[2]/div[2]/div/ul/li[26]/label/span'
exdelt = '//*[@id="screener-criteria"]/div[2]/div[1]/div[1]/div[2]/div/div/div[2]/div[10]/div/ul/li[1]/label/span/span'
xdelt = '//*[@id="screener-criteria"]/div[2]/div[1]/div[1]/div[2]/div/div/div[2]/div/div/ul/li[1]/label/span'
close_filter = '/html/body/div[1]/div/div/div[1]/div/div[2]/div/div/div[5]/div/div/div/div[2]/div[1]/div[1]/div[2]/div/div/div[2]/div/div/ul/li[1]/label/span'
searchbar = '//*[@id="screener-criteria"]/div[2]/div[1]/div[1]/div[2]/div/div/div[1]/div[2]/input'
